
---

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=nguyenmp605@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTP port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt-data/:/letsencrypt/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080", "-O", "-"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 1s
      retries: 12
  hikariita:
    build: https://github.com/nguyenmp/hikariita.git
    volumes:
      - ${HIKARIITA_DB_FILE-/mnt/volume_sfo3_01/hikariita/example.db}:/usr/src/app/example.db
    restart: unless-stopped
    labels:
      - "traefik.http.routers.hikariita.rule=Host(`hikariita.docker.localhost`) || Host(`hikariita.href.cat`)"
      - traefik.http.routers.hikariita.tls=true
      - traefik.http.routers.hikariita.tls.certresolver=myresolver
      - traefik.http.routers.hikariita.tls.domains[0].main=hikariita.href.cat
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 5s
      retries: 12
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www/:/etc/nginx/www/:ro
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
    labels:
      - "traefik.http.routers.nginx.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.nginx.priority=1000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 5s
      retries: 12
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    environment:
      - BASE_URL=changes.href.cat
    volumes:
      - ./changedetection-data/:/datastore/
    restart: unless-stopped
    labels:
      - "traefik.http.routers.changes.rule=Host(`changes.docker.localhost`) || Host(`changes.href.cat`)"
      - traefik.http.routers.changes.tls=true
      - traefik.http.routers.changes.tls.certresolver=myresolver
      - traefik.http.routers.changes.tls.domains[0].main=changes.href.cat
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:5000').raise_for_status()\""]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 1s
      retries: 12

  archivebox:
    build: https://github.com/nguyenmp/ArchiveBox.git#dev
    volumes:
      - ./archivebox-data/:/data/
      # ./data/personas/Default/chrome_profile/Default:/data/personas/Default/chrome_profile/Default
    environment:
      # - ADMIN_USERNAME=admin            # create an admin user on first run with the given user/pass combo
      # - ADMIN_PASSWORD=SomeSecretPassword
      - CSRF_TRUSTED_ORIGINS=https://archivebox.href.cat,https://archivebox.docker.localhost  # REQUIRED for auth, REST API, etc. to work
      - ALLOWED_HOSTS=*                   # set this to the hostname(s) from your CSRF_TRUSTED_ORIGINS
      - PUBLIC_INDEX=True                 # set to False to prevent anonymous users from viewing snapshot list
      - PUBLIC_SNAPSHOTS=True             # set to False to prevent anonymous users from viewing snapshot content
      - PUBLIC_ADD_VIEW=False             # set to True to allow anonymous users to submit new URLs to archive
      - SEARCH_BACKEND_ENGINE=sonic       # tells ArchiveBox to use sonic container below for fast full-text search
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
      # - PUID=911                        # set to your host user's UID & GID if you encounter permissions issues
      # - PGID=911                        # UID/GIDs <500 may clash with existing users and are not recommended
      # - MEDIA_MAX_SIZE=750m             # increase this filesize limit to allow archiving larger audio/video files
      # - TIMEOUT=60                      # increase this number to 120+ seconds if you see many slow downloads timing out
      # - CHECK_SSL_VALIDITY=True         # set to False to disable strict SSL checking (allows saving URLs w/ broken certs)
      # - SAVE_ARCHIVE_DOT_ORG=True       # set to False to disable submitting all URLs to Archive.org when archiving
      # - USER_AGENT="..."                # set a custom USER_AGENT to avoid being blocked as a bot
      # ...
      # add further configuration options from archivebox/config.py as needed (to apply them only to this container)
      # or set using `docker compose run archivebox config --set SOME_KEY=someval` (to persist config across all containers)
    # For ad-blocking during archiving, uncomment this section and pihole service section below
    # networks:
    #   - dns
    # dns:
    #   - 172.20.0.53
    restart: unless-stopped
    labels:
      - "traefik.http.routers.archivebox.rule=Host(`archivebox.docker.localhost`) || Host(`archivebox.href.cat`)"
      - traefik.http.routers.archivebox.tls=true
      - traefik.http.routers.archivebox.tls.certresolver=myresolver
      - traefik.http.routers.archivebox.tls.domains[0].main=archivebox.href.cat
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 5s
      retries: 12
  tor-socks-proxy:
    image: peterdavehello/tor-socks-proxy
    expose:
      - 9150
    restart: unless-stopped
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "icanhazip.com", "-x", "socks5://localhost:9150"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 5s
      retries: 12
  sonic:
    image: valeriansaliou/sonic:latest
    build: .
    expose:
      - 1491
    environment:
      - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
    volumes:
      - ./sonic.cfg:/etc/sonic.cfg:ro    # use this if you prefer to download the config on the host and mount it manually
      - ./sonic-data/sonic:/var/lib/sonic/store
    restart: unless-stopped
    platform: linux/amd64
  cron:
    image: markerz/cronicle
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cron-data/data/:/opt/cronicle/data
      - ./cron-data/logs/:/opt/cronicle/logs
      - ./cron-data/plugins/:/opt/cronicle/plugins
    expose:
      - 3012
    restart: unless-stopped
    labels:
      - "traefik.http.routers.cron.rule=Host(`cron.docker.localhost`) || Host(`cron.href.cat`)"
      - traefik.http.routers.cron.tls=true
      - traefik.http.routers.cron.tls.certresolver=myresolver
      - traefik.http.routers.cron.tls.domains[0].main=cron.href.cat
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3012/"]
      interval: 5s
      timeout: 2s
      start_period: 30s
      start_interval: 5s
      retries: 12

volumes:
  changedetection-data: