---
- name: Deploy VPS services
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping: null

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Add this repository (minus .git) and the rest of this project
      ansible.posix.synchronize:
        src: ./
        dest: ~/vps-management/
        archive: true
        recursive: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=*-data/"

    - name: Install aptitude the preferred manager
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Upgrade system packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: docker compose pull
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env pull
        chdir: ./vps-management/

    - name: docker compose build
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env build
        chdir: ./vps-management/

    - name: docker compose up hikariita
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - hikariita
        remove_orphans: true
        wait: true

    - name: docker compose up postgres-recipes redis
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - postgres-recipes
          - redis
        remove_orphans: true
        wait: true

    - name: docker compose up tor-socks-proxy sockpuppetbrowser
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - tor-socks-proxy
          - sockpuppetbrowser
        remove_orphans: true
        wait: true

    - name: docker compose up n8n n8n-worker
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - n8n
          - n8n-worker
        remove_orphans: true
        wait: true

    - name: docker compose up sparkling-axolotl-jump
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - sparkling-axolotl-jump
        remove_orphans: true
        wait: true

    - name: docker compose up simplearchive
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        services:
          - simplearchive
        remove_orphans: true
        wait: true

    - name: docker compose up (everything else)
      community.docker.docker_compose_v2:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/
        pull: always
        remove_orphans: true
        wait: true

    - name: Prune stopped containers and unused networks
      community.docker.docker_prune:
        containers: true
        networks: true

    - name: Prune unused images
      ansible.builtin.shell:
        cmd: docker image prune -a --force

    - name: Prune dangling builder cache
      ansible.builtin.shell:
        cmd: docker builder prune --filter "dangling=true" --force
