---
- name: Deploy VPS services
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping: null

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Add this repository (minus .git) and the rest of this project
      ansible.posix.synchronize:
        src: ./
        dest: ~/vps-management/
        archive: true
        recursive: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=*-data/"

    - name: Install aptitude the preferred manager
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Upgrade system packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: docker compose pull
      community.docker.docker_compose_v2_pull:
        env_files:
          - ./envs/production.env
        project_src: ./vps-management/

    - name: docker compose build
      ansible.builtin.shell:
        cmd: BUILDX_NO_DEFAULT_ATTESTATIONS=1 docker compose --env-file ./envs/production.env build --pull
        chdir: ./vps-management/

    - name: docker compose up hikariita
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans hikariita
        chdir: ./vps-management/

    - name: docker compose up postgres-recipes redis
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans postgres-recipes redis
        chdir: ./vps-management/

    - name: docker compose up tor-socks-proxy sockpuppetbrowser
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans tor-socks-proxy sockpuppetbrowser
        chdir: ./vps-management/

    - name: docker compose up n8n n8n-worker
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans n8n n8n-worker
        chdir: ./vps-management/

    - name: docker compose up sparkling-axolotl-jump
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans sparkling-axolotl-jump
        chdir: ./vps-management/

    - name: docker compose up simplearchive
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans simplearchive
        chdir: ./vps-management/

    - name: docker compose up (everything else)
      ansible.builtin.shell:
        cmd: docker compose --env-file ./envs/production.env up -d --wait --remove-orphans
        chdir: ./vps-management/

    - name: Prune stopped containers and unused networks
      community.docker.docker_prune:
        containers: true
        networks: true

    - name: Prune unused images
      ansible.builtin.shell:
        cmd: docker image prune --force

    - name: Prune dangling builder cache
      ansible.builtin.shell:
        cmd: docker builder prune --filter "dangling=true" --force
